### ISSUE TITLE
demo amber.py is failing on devel for me

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#1]
I assume this error is related to the fact that I currently have the 17.3 release installed and not the devel branch of Sire?

```
Starting minimisation...
Traceback (most recent call last):
  File "amber.py", line 33, in <module>
    process.start()
  File "/Users/toni_brain/Projects/git/BioSimSpace/python/BioSimSpace/Process/amber.py", line 389, in start
    "%s.out"  % self._name, "%s.err"  % self._name)
Boost.Python.ArgumentError: Python argument types in
    Process.run(str, list, str, str)
did not match C++ signature:
    run(QString command, QStringList arguments)
    run(QString command, QString arg)
    run(QString command)
```

**Comment by lohedges** [comment]
Yes, it requires the devel branch of Sire since I have made some changes to Sire.Base.Process to allow redirection of stdout and stderr. The devel branch also includes pytest.
