### ISSUE TITLE
Obtaining the bond/angle/dihedral information from process

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#296]
**Is your feature request related to a problem? Please describe.**
So I'm interested in using BSS in some analysis script that I use previously which will need bond angle dihedrals.

**Describe the solution you'd like**
The best case would be that the MDAnalysis object would contain all this information. For Gromacs, I would imagine that

```
process = BSS.Process.Gromacs(minimised, protocol)
process.start()
equil = process.getSystem(block=True)
traj = process.getTrajectory()
u = traj.getTrajectory(format='MDAnalysis')
```
The `u` here is the same as
`u = mda.Universe('prod.tpr', 'prod.xtc')` which would contain the bond angle dihedral informations.

**Describe alternatives you've considered**
Or we could just access the output
Like
```
process = BSS.Process.Gromacs(minimised, protocol)
process.start()
equil = process.getSystem(block=True)
traj_dict = process.getOutput()
print(traj_dict)
{'xtc': 'prod.xtc',
 'tpr': 'prod.tpr'
)
```

**Comment by lohedges** [comment]
Hi there,

Thanks for your question. Could you describe in more detail exactly what bond/angle/dihedral information you are trying to extract? Is this just the energies associated with these terms in the potential, or the specific terms in the potential?

If it is the former, then these are accessible from the process object directly using `.getBondEnergy()`, `getAngleEnergy()`, etc. (This extracts information from the log file.) To get a time series of these measurements you can just pass `time_series=True` to any of the methods. Note that the exact methods might differ between engines since they don't all write the same information. A subset are always present, though, so can be used interoperably. (I still need to label these, though.)

```python
process = BSS.Process.Gromacs(minimised, protocol)
process.start()
equil = process.getSystem(block=True)
traj = process.getTrajectory()
u = traj.getTrajectory(format='MDAnalysis')
```

I'm not an `MDAnalysis` expert, so don't know if the universe contains the information that your require. We've tried to design BioSimSpace so that you can extract the underlying information in different common formats, e.g. `MDAnalysis` and `MDTraj` for trajectories, so that you can write workflows with whatever tool you are comfortable with. Does this not work as expected, or does the object not contain the information you expect?

```python
process = BSS.Process.Gromacs(minimised, protocol)
process.start()
equil = process.getSystem(block=True)
traj_dict = process.getOutput()
print(traj_dict)
{'xtc': 'prod.xtc',
 'tpr': 'prod.tpr'
)
```

The `getOutput` method already exists. However, it doesn't return a dictionary, rather an archive (zip file) containing _all_ of the output of the process working directory. If working interactively, this will return a `FileLink` that can be clicked to download the archive to your local machine. Perhaps we could also return a dictionary to give some metadata as to what the files contain.

If you actually need more information on the potential terms then you can access these by querying the properties of the underlying Sire object of a BioSimSpace molecule. Note that this information is a property of the molecular topology, so doesn't change along the trajectory.

```
# Print the bond terms in the potential.
# Here 'molecule' is a BioSimSpace molecule object.
for bond in molecule._sire_object.property("bond").potentials():
    print(bond)
```

This will give something like:

```
TwoAtomFunction( {CGIdx(0),Index(4)} <-> {CGIdx(0),Index(5)} : 570 [r - 1.229]^2 )
TwoAtomFunction( {CGIdx(1),Index(2)} <-> {CGIdx(1),Index(4)} : 310 [r - 1.526]^2 )
TwoAtomFunction( {CGIdx(0),Index(4)} <-> {CGIdx(1),Index(0)} : 490 [r - 1.335]^2 )
TwoAtomFunction( {CGIdx(0),Index(0)} <-> {CGIdx(0),Index(1)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(2),Index(2)} <-> {CGIdx(2),Index(5)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(2),Index(2)} <-> {CGIdx(2),Index(4)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(1),Index(8)} <-> {CGIdx(2),Index(0)} : 490 [r - 1.335]^2 )
TwoAtomFunction( {CGIdx(2),Index(2)} <-> {CGIdx(2),Index(3)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(1),Index(4)} <-> {CGIdx(1),Index(7)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(1),Index(8)} <-> {CGIdx(1),Index(9)} : 570 [r - 1.229]^2 )
TwoAtomFunction( {CGIdx(1),Index(4)} <-> {CGIdx(1),Index(6)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(1),Index(0)} <-> {CGIdx(1),Index(2)} : 337 [r - 1.449]^2 )
TwoAtomFunction( {CGIdx(1),Index(4)} <-> {CGIdx(1),Index(5)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(1),Index(0)} <-> {CGIdx(1),Index(1)} : 434 [r - 1.01]^2 )
TwoAtomFunction( {CGIdx(2),Index(0)} <-> {CGIdx(2),Index(1)} : 434 [r - 1.01]^2 )
TwoAtomFunction( {CGIdx(0),Index(1)} <-> {CGIdx(0),Index(4)} : 317 [r - 1.522]^2 )
TwoAtomFunction( {CGIdx(2),Index(0)} <-> {CGIdx(2),Index(2)} : 337 [r - 1.449]^2 )
TwoAtomFunction( {CGIdx(0),Index(1)} <-> {CGIdx(0),Index(3)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(1),Index(2)} <-> {CGIdx(1),Index(8)} : 317 [r - 1.522]^2 )
TwoAtomFunction( {CGIdx(1),Index(2)} <-> {CGIdx(1),Index(3)} : 340 [r - 1.09]^2 )
TwoAtomFunction( {CGIdx(0),Index(1)} <-> {CGIdx(0),Index(2)} : 340 [r - 1.09]^2 )
...
```

**Comment by xiki-tempula** [comment]
Thanks for the explanation. What I want is more like the `molecule._sire_object.property("bond")` which tells me which two atoms are bonded, which three atoms form an angle and which four atoms form a dihedral and I can get their value conveniently inside a trajectory. The current analysis script is written based on MDAnalysis so it would be really nice if I could use it.

I was wondering why do you feed the gro file into the MDAnalysis instead of the tpr file?

**Comment by lohedges** [comment]
Thanks for the clarification. You should be able to use `MDAnalysis` using the approach you suggest, i.e.:

```python
process = BSS.Process.Gromacs(minimised, protocol)
process.start()
equil = process.getSystem(block=True)
traj = process.getTrajectory()
u = traj.getTrajectory(format='MDAnalysis')
```

Is this not working? If not, could you post the error message and some example input so that I can debug.

> I was wondering why do you feed the gro file into the MDAnalysis instead of the tpr file?

We pass in both, i.e.:

```
universe = _mdanalysis.Universe(top_file, traj_file)
```

where `top_file` in this case is the Gro87 format file, which `MDAnalysis` uses to define the list of atoms. See [here](https://docs.mdanalysis.org/0.20.1/documentation_pages/core/universe.html) for details of the `Universe` class.

You can certainly get the indices of atoms involved in bonds, angles, dihedrals, etc., directly through Sire. I guess `MDAnalysis` gives you the contribution of each to the potential at each time step too?

Cheers.

**Comment by xiki-tempula** [comment]
Ok, I don't know why MDAnalysis write the documentation in this way but MDAnalysis do take tpr file as topology
```
>>> u = mda.Universe('gromacs.gro')
>>> u.atoms.bonds
Traceback (most recent call last):
  File "/Users/zwu/miniconda3_x86/envs/exs-orionbssfloes/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-f2834017ae0e>", line 1, in <module>
    u.atoms.bonds
  File "/Users/zwu/miniconda3_x86/envs/exs-orionbssfloes/lib/python3.7/site-packages/MDAnalysis/core/groups.py", line 2535, in __getattr__
    return super(AtomGroup, self).__getattr__(attr)
  File "/Users/zwu/miniconda3_x86/envs/exs-orionbssfloes/lib/python3.7/site-packages/MDAnalysis/core/groups.py", line 609, in __getattr__
    raise NoDataError(err.format(singular=cls.singular))
MDAnalysis.exceptions.NoDataError: This Universe does not contain bonds information
```
```
>>> u = mda.Universe('gromacs.tpr', 'gromacs.gro')
>>> u.atoms.bonds
<TopologyGroup containing 22891 bonds>
```

**Comment by lohedges** [comment]
Thanks for this, I just saw the same thing here. It looks like their documentation is wrong, since the topology (GRO in this instance as a _structure_ file) is listed as the _first_ argument, not the second. I'll test at my end with the reversed input to see if I can get it to work.

**Comment by lohedges** [comment]
Thanks, I'll update the code and close this when the change is pushed.
