### ISSUE TITLE
amber.py demo hangs with minimisation OSX

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#3]
It seems that there is an issue with threading, because I can't seem to go beyond the minimisation in the demo when running sire as
```python amber.py```

The error I get:
```
Loading molecules...

Initialising minimisation process...

Created AMBER input files: ['minimise/minimise.amber', 'minimise/minimise.rst7', 'minimise/minimise.prm7']

Starting minimisation...
^CTraceback (most recent call last):
  File "amber.py", line 41, in <module>
    process.wait()
  File "/Users/toni_brain/Projects/git/BioSimSpace/python/BioSimSpace/Process/amber.py", line 652, in wait
    self._watcher._observer.join()
  File "/Users/toni_brain/sire.app_dev_17.3/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/Users/toni_brain/sire.app_dev_17.3/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by lohedges** [comment]
This appears to be a problem with using Sire.Base.Process.wait() with the background thread that the BioSimSpace.Process.Amber object uses to watch log files. I fixed it by manually waiting for the process to finish before shutting down the watchdog, i.e. without using Sire.Base.Process.wait().
