### ISSUE TITLE
BioSimSpace won't import

### ISSUE THREAD

**Issue by chryswoods** [michellab/BioSimSpace#7]
After reinstalling mdtraj I now can't import BioSimSpace because "plt" is not defined (see below). This was all working yesterday evening (as was mdtraj)...

```
:-> docker run -it --rm -p 8888:8888 chryswoods/bss-workshop bash
jovyan@b8d6a5813033:~$ update_workshops
Updating BioSimSpace and all workshops...
  -- [u] BioSimSpace
Already up-to-date.

  -- [u] xswaps
Already up-to-date.

Everything updated :-)
jovyan@b8d6a5813033:~$ conda install mdtraj
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - mdtraj


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mdtraj-1.9.1               |           py35_1         5.9 MB  conda-forge

The following packages will be UPDATED:

    mdtraj: 1.9.1-py35_0 omnia --> 1.9.1-py35_1 conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
mdtraj 1.9.1: #################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
jovyan@b8d6a5813033:~$ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import BioSimSpace
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-99da57a799ef> in <module>()
----> 1 import BioSimSpace

/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.321.g64c461a-py3.5.egg/BioSimSpace/__init__.py in <module>()
     28 
     29 import BioSimSpace.Gateway
---> 30 import BioSimSpace.Notebook
     31 import BioSimSpace.Process
     32 import BioSimSpace.Protocol

/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.321.g64c461a-py3.5.egg/BioSimSpace/Notebook/__init__.py in <module>()
----> 1 from .plot import Plot
      2 from .view import View

/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.321.g64c461a-py3.5.egg/BioSimSpace/Notebook/plot.py in <module>()
     18 
     19 # Set font sizes.
---> 20 plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
     21 plt.rc('axes', titlesize=SMALL_SIZE)     # fontsize of the axes title
     22 plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels

NameError: name 'plt' is not defined

In [2]:                                                                                   
Do you really want to exit ([y]/n)? y
jovyan@b8d6a5813033:~$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import BioSimSpace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.321.g64c461a-py3.5.egg/BioSimSpace/__init__.py", line 30, in <module>
    import BioSimSpace.Notebook
  File "/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.321.g64c461a-py3.5.egg/BioSimSpace/Notebook/__init__.py", line 1, in <module>
    from .plot import Plot
  File "/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.321.g64c461a-py3.5.egg/BioSimSpace/Notebook/plot.py", line 20, in <module>
    plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
NameError: name 'plt' is not defined
>>> 
```

**Comment by chryswoods** [comment]
Thanks. No rush. I just put the issue up so that I didn't forget.

**Comment by chryswoods** [comment]
Thanks -  I can confirm that your commit has fixed things. Yes, I split this from #6 as they didn't have a common origin (#6 was, as you said, a docker issue with corruption on OS X, and not related to BSS).

These issues are making me rethink our use of try_import, and how we handle python dependencies. It is a challenging problem, especially as conda will upgrade already-installed packages (e.g. I had to downgrade tornado to get jupyterhub working as it had been upgraded by matplotlib or something similar). We should have a whiteboarding session after the workshops to come up with ideas.
