### ISSUE TITLE
BioSimSpace - clearer parsing error reports?

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#8]
In the BSS tutorial first notebook the following incorrectly formatted instructions (top file missing) 
!python nodes/minimisation.py --steps=1000 --files input/ala.crd
will generate a cryptic Sire traceback for the user. 

Traceback (most recent call last):
  File "nodes/minimisation.py", line 69, in <module>
    system = BSS.readMolecules(node.getInput("files"))
  File "/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.340.g3404973-py3.5.egg/BioSimSpace/__init__.py", line 46, in readMolecules
    return Sire.IO.MoleculeParser.read( files )
UserWarning: Exception 'SireError::program_bug' thrown by the thread 'master'.
There are no lead parsers!
(...)

It would be good to catch this and report a more helpful error message for the user (such as "you provided a .crd file but no .top file" etc...)

**Comment by jmichel80** [comment]
For completeness this error could also be caught

!python nodes/minimisation.py --steps=1000 --files input/ala.top

Traceback (most recent call last):
  File "nodes/minimisation.py", line 85, in <module>
    process = BSS.MD.run(system, protocol)
  File "/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.340.g3404973-py3.5.egg/BioSimSpace/Driver/md.py", line 115, in run
    package, exe = _find_md_package(system, protocol)
  File "/opt/conda/lib/python3.5/site-packages/BioSimSpace-0+untagged.340.g3404973-py3.5.egg/BioSimSpace/Driver/md.py", line 54, in _find_md_package
    raise ValueError("Cannot find an MD package that supports format: %s" % fileformat)
ValueError: Cannot find an MD package that supports format: PRM7

**Comment by jmichel80** [comment]
!python nodes/minimisation.py --help should report the minimum and maximum number of steps allowed as well as the default number of steps
